### PR TITLE
Fix complex method in Day8.js

### LINKED ISSUE #9: Fix Complex Method Day8.js
[CodeFactor](https://www.codefactor.io/repository/github/v-dat/30days) found an issue: Complex Method

It's currently on:
[src\pages\Day8\Day8.js:66-81](https://www.codefactor.io/repository/github/v-dat/30days/source/Master/src/pages/Day8/Day8.js#L66)

### PR DESCRIPTION
**Pull request by dat-dv**
I made some changes in Day8.js

- Remove hook unuse : useMemo, useCallback 
- Move Function handleControl to object controlActions
- Fix function handleClickSong

### CODE REVIEW

**Comment by dat-dv** [comment]
@nhathuy13598  Please help me merge this PR

**Comment by nhathuy13598** [comment]
I think this code is not good. What happens if we want to reuse music player in another component? @V-Dat. You need to watch [this video](https://reactjs.org/docs/hooks-intro.html#video-introduction), it will teach you how to write clean code with Hooks

**Comment by dat-dv** [comment]
Please help me merge this PR

**Comment by nhathuy13598** [comment]
Although having some issues but I will merge this branch and consider to fix them later

**Pull request merged**
