### PR TITLE
use git lfs for binary files like mp3, jpg, png

### LINKED ISSUE #2: Using Git LFS for binary files like .png, .mp3
All binary files in repo should be manged by Git LFS. Search more https://git-lfs.github.com/

### LINKED ISSUE #24: Merge branch gitLFS to master
- Merge branch gitLFS to master

### PR DESCRIPTION
**Pull request by dat-dv**
use git lfs for binary files like mp3, jpg, png

### CODE REVIEW

**Comment by nhathuy13598** [comment]
Please remove changes not related to this issue @V-Dat

**Comment by dat-dv** [comment]
> Please remove changes not related to this issue @V-Dat

i've removed!

**Comment by nhathuy13598** [comment]
> > Please remove changes not related to this issue @V-Dat
> 
> i've removed!

I still see unrelated changes in some file .css and .js in this branch @V-Dat

**Comment by dat-dv** [comment]
> > > Please remove changes not related to this issue @V-Dat
> > 
> > 
> > i've removed!
> 
> I still see unrelated changes in some file .css and .js in this branch @V-Dat

**Comment by dat-dv** [comment]
> > > > Please remove changes not related to this issue @V-Dat
> > > 
> > > 
> > > i've removed!
> > 
> > 
> > I still see unrelated changes in some file .css and .js in this branch @V-Dat
> i've removed please check agains.

**Pull request merged**
